{ pkgs, ... }:
{
  imports = [
    ./kde
    ./cosmic
    ./hyprland
  ];

  # ── Display Manager ───────────────────────────────────────────────────────────
  # XServer is required to run SDDM even on Wayland sessions
  services.xserver.enable = true;
  # SDDM is the shared display manager for both KDE and COSMIC sessions
  services.displayManager.sddm.enable = true;
  # Default session: hyprland (use "plasmax11" for KDE X11, "plasma" for KDE Wayland)
  services.displayManager.defaultSession = "hyprland";

  # To replace SDDM with the COSMIC greeter instead:
  #   1. Set services.displayManager.sddm.enable = false above
  #   2. Uncomment the line below
  # services.displayManager.cosmic-greeter.enable = true;

  # XWayland allows X11 apps to run inside a Wayland session
  programs.xwayland.enable = true;

  # ── XDG Desktop Portal ────────────────────────────────────────────────────────
  # Ref: https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland/
  # Ref: https://wiki.archlinux.org/title/XDG_Desktop_Portal
  # Ref: https://flatpak.github.io/xdg-desktop-portal/
  #
  # Background: Why apps can't talk to the compositor directly
  # ──────────────────────────────────────────────────────────
  # On Wayland, applications are strictly sandboxed — they cannot access the
  # compositor (Hyprland), the filesystem, or system features directly. Instead,
  # they make requests through a trusted intermediary: xdg-desktop-portal (XDP).
  # XDP listens on D-Bus and forwards requests to the appropriate backend
  # (called a "portal implementation") that actually talks to the compositor.
  #
  #   ┌─────────────────────────────────────────────────────────────────────┐
  #   │                                                                     │
  #   │  Firefox ──── D-Bus ────► xdg-desktop-portal ──► portal backend   │
  #   │                                                                     │
  #   │  (sandboxed app)          (trusted broker)        (talks to DE)    │
  #   │                                                                     │
  #   └─────────────────────────────────────────────────────────────────────┘
  #
  # Portal implementations (backends)
  # ──────────────────────────────────
  # Each portal implementation handles a specific set of D-Bus interfaces.
  # No single portal covers everything, so multiple backends coexist:
  #
  #   ┌──────────────────────────────┬───────────────────────────────────────┐
  #   │ Interface                    │ Who handles it                        │
  #   ├──────────────────────────────┼───────────────────────────────────────┤
  #   │ ScreenCopy (screen sharing)  │ XDPH  (needs compositor access)       │
  #   │ Screenshot                   │ XDPH  (needs compositor access)       │
  #   │ GlobalShortcuts              │ XDPH  (needs compositor access)       │
  #   │ FileChooser (file dialogs)   │ -gtk  (DE-agnostic, no compositor)    │
  #   │ OpenURI (open with...)       │ -gtk  (DE-agnostic, no compositor)    │
  #   │ Settings (theme/font/color)  │ -gtk  (DE-agnostic, no compositor)    │
  #   └──────────────────────────────┴───────────────────────────────────────┘
  #
  #   XDPH = xdg-desktop-portal-hyprland
  #   -gtk  = xdg-desktop-portal-gtk
  #
  # Concrete example: "Firefox opens a file dialog"
  # ────────────────────────────────────────────────
  # 1. User clicks "Open File" in Firefox
  # 2. Firefox sends:  org.freedesktop.portal.FileChooser.OpenFile  via D-Bus
  # 3. XDP resolver checks hyprland-portals.conf (auto-generated by NixOS):
  #      [preferred]
  #      default=hyprland;gtk       ← try XDPH first, then gtk
  # 4. XDPH: "I don't implement FileChooser" → skipped
  # 5. -gtk: "I implement FileChooser" → opens GTK file picker dialog ✓
  #
  # What happens WITHOUT xdg-desktop-portal-gtk
  # ────────────────────────────────────────────
  # Step 4 above: XDPH doesn't handle it.
  # Step 5: no fallback exists → XDP waits for a response that never comes.
  # Result: every app that touches FileChooser (or OpenURI, Settings, etc.)
  # blocks for 5–30 seconds on launch while the request times out.
  # This makes ALL apps feel slow to start, even before the window appears.
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-gtk
    ];
  };

  # US keyboard layout for X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };
}
