# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running 'nixos-help').
{
  config,
  pkgs,
  username,
  ...
}:
{
  imports = [
    # Hardware scan results - auto-generated by nixos-generate-config
    ./hardware-configuration.nix
    # Declarative disk partitioning (disabled - partitions are already set up)
    # ./disko-config.nix
  ];

  # ── Boot ─────────────────────────────────────────────────────────────────────
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };
  # Clear /tmp on every boot for a clean state
  boot.tmp.cleanOnBoot = true;

  # ── Nix Settings ──────────────────────────────────────────────────────────────
  nix = {
    settings = {
      auto-optimise-store = true; # Deduplicate identical files in the Nix store
      # Enable nix-command (new Nix CLI) and flakes support
      experimental-features = [
        "nix-command"
        "flakes"
      ];
    };
    # Run garbage collection weekly, deleting generations older than 7 days
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
  };

  # Allow installing non-free (proprietary) packages
  nixpkgs.config.allowUnfree = true;

  # ── Network ───────────────────────────────────────────────────────────────────
  # Replace "nixos" with your actual hostname
  networking.hostName = "nixos";
  # systemd-resolved - required for NetworkManager DNS resolution
  services.resolved.enable = true;
  networking.networkmanager.enable = true;
  # Force DNS to Cloudflare (1.1.1.1) for reliable resolution
  networking.resolvconf.extraConfig = "name_servers=1.1.1.1";

  # ── Locale ────────────────────────────────────────────────────────────────────
  time.timeZone = "Asia/Tokyo";

  # ── Desktop ───────────────────────────────────────────────────────────────────
  # XServer is required to run SDDM and KDE Plasma even on Wayland
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;
  # Use X11 session; change to "plasma" to switch to Wayland
  services.displayManager.defaultSession = "plasmax11";
  # XWayland allows X11 apps to run inside a Wayland session
  programs.xwayland.enable = true;
  xdg.portal = {
    # Required by Flatpak for sandboxed file chooser, screenshot, etc.
    # KDE automatically provides xdg-desktop-portal-kde; no extra portals needed here
    enable = true;
    # extraPortals = with pkgs; [
    #   xdg-desktop-portal-gtk  # Add this on non-KDE/GNOME desktops
    # ];
  };

  # US keyboard layout for X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # ── Hardware ──────────────────────────────────────────────────────────────────
  # Enable CUPS print server
  services.printing.enable = true;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true; # Power on Bluetooth controller automatically at boot
  };

  # Enable GPU acceleration (OpenGL/Vulkan)
  hardware.graphics.enable = true;

  # ── Audio ─────────────────────────────────────────────────────────────────────
  # PipeWire replaces PulseAudio for modern low-latency audio support
  services.pulseaudio.enable = false;
  security.rtkit.enable = true; # Real-time scheduling priority, required by PipeWire
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true; # Required for 32-bit applications (e.g., Wine/Steam)
    pulse.enable = true; # PulseAudio-compatible interface for legacy apps
    jack.enable = true; # JACK-compatible interface for professional audio apps
  };
  # Real-time noise suppression for microphone input
  programs.noisetorch.enable = true;

  # ── Users ─────────────────────────────────────────────────────────────────────
  users.defaultUserShell = "/run/current-system/sw/bin/zsh";
  # Allow users to change their own passwords via the passwd command
  users.mutableUsers = true;
  users.users.${username} = {
    isNormalUser = true;
    description = "${username}";
    # Generate a new hash with: mkpasswd -m sha-512
    initialHashedPassword = "$6$DEgxVwM7CWGRVNK6$f/ATlexID21R3DJ7NfQEbnvZ3dakf1Ejro5yPimllGLg2zUqJ5aCjuBxF4QaXOLnXoPc46n.7WLXZmBnuInZ81";
    # wheel: sudo access | networkmanager: manage Wi-Fi/Ethernet | flatpak/incus-admin: service access
    extraGroups = [
      "networkmanager"
      "wheel"
      "flatpak"
      "incus-admin"
    ];
    shell = "/run/current-system/sw/bin/zsh";
  };
  # Required for VirtualBox USB devices, Docker socket, and libvirt management
  users.extraGroups.vboxusers.members = [
    "${username}"
    "docker"
    "libvirtd"
  ];

  # ── Services ──────────────────────────────────────────────────────────────────
  # Flatpak - sandboxed desktop application installation from Flathub
  services.flatpak.enable = true;

  # Tailscale - zero-config mesh VPN
  services.tailscale.enable = true;
  environment.systemPackages = with pkgs; [
    tailscale # CLI tools for managing Tailscale connections
  ];

  # OpenSSH - allow remote login via SSH
  services.openssh.enable = true;

  # ── Virtualisation ────────────────────────────────────────────────────────────
  virtualisation = {
    docker.enable = true;
    waydroid.enable = true; # Run Android apps on Linux via a container
    incus = {
      enable = true;
      ui.enable = true; # Enable the Incus web UI (accessible at https://localhost:8443)
    };
  };

  # KVM / QEMU virtual machine management via virt-manager
  # Ref: https://nixos.wiki/wiki/Virt-manager
  programs.virt-manager.enable = true;
  # Note: "hello" is hardcoded here - update this if the username changes
  users.groups.libvirtd.members = [ "hello" ];
  virtualisation = {
    libvirtd.enable = true;
    spiceUSBRedirection.enable = true; # USB passthrough support for virtual machines
  };

  # Fingerprint reader (disabled - driver compatibility issues on this hardware)
  # services.fprintd = {
  #   enable = true;
  #   package = pkgs.fprintd-tod;
  #   tod = {
  #     enable = true;
  #     driver = pkgs.libfprint-2-tod1-vfs0090;
  #   };
  # };

  # ── Firewall ──────────────────────────────────────────────────────────────────
  networking.firewall = {
    enable = true;
    trustedInterfaces = [
      "tailscale0" # Tailscale virtual NIC - fully trusted for mesh VPN traffic
      "incusbr0" # Incus bridge NIC - trusted for container networking
    ];
    allowedUDPPorts = [
      config.services.tailscale.port # Tailscale (dynamic port, read from service config)
      51820 # WireGuard VPN
    ];
    # KDE Connect - file transfer and notification sync with mobile devices (ports 1714-1764)
    allowedTCPPortRanges = [
      {
        from = 1714;
        to = 1764;
      }
    ];
  };
  # WireGuard VPN config file (contains keys and peer addresses - keep this file private)
  networking.wg-quick.interfaces.wg0.configFile = "/home/hello/Documents/Myxogastria0808-NixOS.conf";
  # nftables is required by Incus (it uses nftables instead of iptables for container networking)
  networking.nftables.enable = true;

  # ── State Version ─────────────────────────────────────────────────────────────
  # Determines the NixOS release from which default settings for stateful data
  # (file locations, database versions) are taken. Do not change this after the
  # initial install unless you fully understand the implications.
  # See: https://nixos.org/nixos/options.html
  system.stateVersion = "26.05";
}
