# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running 'nixos-help').
{
  pkgs,
  username,
  ...
}:
{
  imports = [
    # Hardware scan results - auto-generated by nixos-generate-config
    ./hardware-configuration.nix
    # Declarative disk partitioning (disabled - partitions are already set up)
    # ./disko-config.nix
  ];

  # ── Boot ─────────────────────────────────────────────────────────────────────
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # Use the latest Linux kernel
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Clear /tmp on every boot for a clean state
  boot.tmp.cleanOnBoot = true;

  # ── Nix Settings ──────────────────────────────────────────────────────────────
  nix = {
    settings = {
      auto-optimise-store = true; # Deduplicate identical files in the Nix store
      # Enable nix-command (new Nix CLI) and flakes support
      experimental-features = [
        "nix-command"
        "flakes"
      ];
    };
    # Run garbage collection weekly, deleting generations older than 7 days
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
  };

  # Allow installing non-free (proprietary) packages
  nixpkgs.config.allowUnfree = true;

  # ── Network ───────────────────────────────────────────────────────────────────
  # Replace "nixos" with your actual hostname
  networking.hostName = "nixos";
  # systemd-resolved - required for NetworkManager DNS resolution
  services.resolved.enable = true;
  networking.networkmanager.enable = true;
  # Force DNS to Cloudflare (1.1.1.1) for reliable resolution
  networking.resolvconf.extraConfig = "name_servers=1.1.1.1";

  # ── Locale ────────────────────────────────────────────────────────────────────
  time.timeZone = "Asia/Tokyo";

  # ── Hardware ──────────────────────────────────────────────────────────────────
  # Enable CUPS print server
  services.printing.enable = true;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true; # Power on Bluetooth controller automatically at boot
  };

  # Enable GPU acceleration (OpenGL/Vulkan).
  hardware.graphics.enable = true;

  # ── Users ─────────────────────────────────────────────────────────────────────
  users.defaultUserShell = "/run/current-system/sw/bin/zsh";
  # Allow users to change their own passwords via the passwd command
  users.mutableUsers = true;
  users.users.${username} = {
    isNormalUser = true;
    description = "${username}";
    # Generate a new hash with: mkpasswd -m sha-512
    initialHashedPassword = "$6$DEgxVwM7CWGRVNK6$f/ATlexID21R3DJ7NfQEbnvZ3dakf1Ejro5yPimllGLg2zUqJ5aCjuBxF4QaXOLnXoPc46n.7WLXZmBnuInZ81";
    extraGroups = [
      "networkmanager"
      "wheel"
      "flatpak"
      "incus-admin" # daemon enabled in modules/config/incus.nix
      "libvirtd" # demon enabled in modules/config/kvm.nix
    ];
    shell = "/run/current-system/sw/bin/zsh";
  };

  # ── Services ──────────────────────────────────────────────────────────────────
  # Flatpak - sandboxed desktop application installation from Flathub
  services.flatpak.enable = true;

  # ── Secret Service (keyring) ──────────────────────────────────────────────────
  # gnome-keyring provides a D-Bus secret service (org.freedesktop.secrets) that
  # stores credentials (OAuth tokens, SSH keys, etc.) in an encrypted keystore.
  # KDE provided this via kwallet; without KDE, tools like `gh`, `git-credential`,
  # and many GUI apps cannot persist credentials between sessions without this.
  # PAM integration unlocks the keyring automatically at login via SDDM.
  services.gnome.gnome-keyring.enable = true;
  security.pam.services.sddm.enableGnomeKeyring = true;

  # Tailscale and WireGuard VPN are managed in modules/config/tailscale.nix
  # and modules/config/wireguard.nix. Toggle via enableTailscale / enableWireGuard in flake.nix.

  # OpenSSH - allow remote login via SSH
  services.openssh.enable = true;

  # ── CPU Scheduler (sched_ext / SCX) ──────────────────────────────────────────
  # NOTE: This explanation was generated by **Claude**, so it may contain errors.
  #
  # sched_ext is a Linux kernel framework (merged in 6.12) that lets you load
  # an alternative CPU scheduler as an eBPF program at runtime — no kernel
  # recompilation, no reboot required.  If the BPF scheduler crashes or stalls,
  # the kernel watchdog automatically reverts all tasks to EEVDF (the default
  # scheduler).  Backed by Meta, Google, and Valve/Igalia.
  #
  # [Background: BPF and eBPF]
  # BPF (Berkeley Packet Filter, 1992) was a minimal kernel VM for network
  # packet filtering — its key property was that programs were proven safe at
  # load time and could never crash the kernel.  eBPF (extended BPF, 2014)
  # kept that safety model but expanded into a general-purpose kernel
  # programmability layer: 64-bit registers, JIT compiler, typed maps shared
  # between kernel and userspace, and a formal verifier.  sched_ext applies
  # this to CPU scheduling: the scheduler is an eBPF program, so its safety
  # is guaranteed before it ever touches a task.
  #
  # Architecture overview:
  #
  #  ┌─────────────────────────────────────────────────────────────────────┐
  #  │                        KERNEL SPACE                                 │
  #  │                                                                     │
  #  │   ┌────────────────────┐        ┌──────────────────────────────┐    │
  #  │   │       EEVDF        │        │        sched_ext class       │    │
  #  │   │  Default scheduler │        │  (BPF hooks: select_cpu,     │    │
  #  │   │  (always present)  │        │   enqueue, dispatch, ...)    │    │
  #  │   └────────────────────┘        └──────────────┬───────────────┘    │
  #  │           ▲  fallback                          │                    │
  #  │           │  on crash/stall                    ▼                    │
  #  │           │                     ┌──────────────────────────────┐    │
  #  │           │                     │   eBPF runtime               │    │
  #  │           │                     │   • Verifier (safety check)  │    │
  #  │           │                     │   • JIT compiler             │    │
  #  │           │                     └──────────────┬───────────────┘    │
  #  └───────────┼────────────────────────────────────┼────────────────────┘
  #              │                                    │ load / unload
  #  ┌───────────┼────────────────────────────────────┼───────────────────┐
  #  │           │             USER SPACE             │                   │
  #  │           │   ┌────────────────────────────────▼─────────────┐     │
  #  │           │   │  ┌─────────────┐  ┌──────────┐  ┌─────────┐  │     │
  #  │           │   │  │ scx_bpfland │  │ scx_lavd │  │scx_rusty│  │     │
  #  │           │   │  │ Interactive │  │Gaming/HW │  │  Multi- │  │     │
  #  │           │   │  └─────────────┘  └──────────┘  │  domain │  │     │
  #  │           │   │                                 └─────────┘  │     │
  #  │           │   │  ┌───────────────────────────────────────┐   │     │
  #  │           │   │  │  scx_loader (D-Bus daemon)            │   │     │
  #  │           │   └──┴───────────────────────────────────────┴───┘     │
  #  └───────────┼────────────────────────────────────────────────────────┘
  #              └── watchdog fires → auto-revert to EEVDF
  #
  # scx_bpfland is chosen because Hyprland's compositor thread wakes 60–144
  # times/sec, automatically landing in the interactive queue — no config needed.
  # scx_lavd is a strong alternative if you game frequently:
  #   sudo scx_lavd --autopilot
  #
  # WARNING: Do NOT combine with ananicy-cpp — they amplify each other's priority
  #    boosts and risk triggering the watchdog.
  #
  # Verify: cat /sys/kernel/sched_ext/state   ("enabled" = scheduler is live)
  #         scx_bpfland --monitor 1           (live per-CPU stats)
  #
  services.scx = {
    enable = true;
    scheduler = "scx_bpfland";
  };

  # Fingerprint reader (disabled - driver compatibility issues on this hardware)
  # services.fprintd = {
  #   enable = true;
  #   package = pkgs.fprintd-tod;
  #   tod = {
  #     enable = true;
  #     driver = pkgs.libfprint-2-tod1-vfs0090;
  #   };
  # };

  # ── Firewall ──────────────────────────────────────────────────────────────────
  # Rules for Tailscale, WireGuard, and Incus are each managed by their own modules
  # (modules/config/{tailscale,wireguard,incus}.nix). nftables is also enabled there.
  networking.firewall.enable = true;

  # ── State Version ─────────────────────────────────────────────────────────────
  # Determines the NixOS release from which default settings for stateful data
  # (file locations, database versions) are taken. Do not change this after the
  # initial install unless you fully understand the implications.
  # See: https://nixos.org/nixos/options.html
  system.stateVersion = "25.11";
}
