# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running 'nixos-help').
{
  config,
  pkgs,
  username,
  ...
}:
{
  imports = [
    # Hardware scan results - auto-generated by nixos-generate-config
    ./hardware-configuration.nix
    # Declarative disk partitioning (disabled - partitions are already set up)
    # ./disko-config.nix
  ];

  # ── Boot ─────────────────────────────────────────────────────────────────────
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };
  # NOTE: temporary settings
  # linux-zen: performance-optimized kernel with better scheduling responsiveness
  # Reduces app freezes and input latency compared to the standard kernel
  # boot.kernelPackages = pkgs.linuxPackages_zen;

  # Clear /tmp on every boot for a clean state
  boot.tmp.cleanOnBoot = true;

  # ── Nix Settings ──────────────────────────────────────────────────────────────
  nix = {
    settings = {
      auto-optimise-store = true; # Deduplicate identical files in the Nix store
      # Enable nix-command (new Nix CLI) and flakes support
      experimental-features = [
        "nix-command"
        "flakes"
      ];
    };
    # Run garbage collection weekly, deleting generations older than 7 days
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
  };

  # Allow installing non-free (proprietary) packages
  nixpkgs.config.allowUnfree = true;

  # ── Network ───────────────────────────────────────────────────────────────────
  # Replace "nixos" with your actual hostname
  networking.hostName = "nixos";
  # systemd-resolved - required for NetworkManager DNS resolution
  services.resolved.enable = true;
  networking.networkmanager.enable = true;
  # Force DNS to Cloudflare (1.1.1.1) for reliable resolution
  networking.resolvconf.extraConfig = "name_servers=1.1.1.1";

  # ── Locale ────────────────────────────────────────────────────────────────────
  time.timeZone = "Asia/Tokyo";

  # ── Hardware ──────────────────────────────────────────────────────────────────
  # Enable CUPS print server
  services.printing.enable = true;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true; # Power on Bluetooth controller automatically at boot
  };

  # Enable GPU acceleration (OpenGL/Vulkan).
  hardware.graphics.enable = true;

  # NOTE: temporary settings
  # Use mesa from Hyprland flake's own nixpkgs input to avoid version mismatch
  # between the compositor and the graphics driver, which causes GPU rendering
  # instability, lag, and XWayland freezes.
  # Ref: https://wiki.hypr.land/Nix/Hyprland-on-NixOS/
  # hardware.graphics = {
  #   enable = true;
  #   package = (inputs.hyprland.inputs.nixpkgs.legacyPackages.${pkgs.stdenv.hostPlatform.system}.mesa);
  # };

  # ── Users ─────────────────────────────────────────────────────────────────────
  users.defaultUserShell = "/run/current-system/sw/bin/zsh";
  # Allow users to change their own passwords via the passwd command
  users.mutableUsers = true;
  users.users.${username} = {
    isNormalUser = true;
    description = "${username}";
    # Generate a new hash with: mkpasswd -m sha-512
    initialHashedPassword = "$6$DEgxVwM7CWGRVNK6$f/ATlexID21R3DJ7NfQEbnvZ3dakf1Ejro5yPimllGLg2zUqJ5aCjuBxF4QaXOLnXoPc46n.7WLXZmBnuInZ81";
    # wheel: sudo access | networkmanager: manage Wi-Fi/Ethernet | flatpak/incus-admin: service access
    extraGroups = [
      "networkmanager"
      "wheel"
      "flatpak"
      "incus-admin"
    ];
    shell = "/run/current-system/sw/bin/zsh";
  };

  # ── Services ──────────────────────────────────────────────────────────────────
  # Flatpak - sandboxed desktop application installation from Flathub
  services.flatpak.enable = true;

  # Tailscale - zero-config mesh VPN
  services.tailscale.enable = true;
  environment.systemPackages = with pkgs; [
    tailscale # CLI tools for managing Tailscale connections
  ];

  # OpenSSH - allow remote login via SSH
  services.openssh.enable = true;

  # Fingerprint reader (disabled - driver compatibility issues on this hardware)
  # services.fprintd = {
  #   enable = true;
  #   package = pkgs.fprintd-tod;
  #   tod = {
  #     enable = true;
  #     driver = pkgs.libfprint-2-tod1-vfs0090;
  #   };
  # };

  # ── Firewall ──────────────────────────────────────────────────────────────────
  networking.firewall = {
    enable = true;
    trustedInterfaces = [
      "tailscale0" # Tailscale virtual NIC - fully trusted for mesh VPN traffic
      "incusbr0" # Incus bridge NIC - trusted for container networking
    ];
    allowedUDPPorts = [
      config.services.tailscale.port # Tailscale (dynamic port, read from service config)
      51820 # WireGuard VPN
    ];
  };
  # WireGuard VPN config file (contains keys and peer addresses - keep this file private)
  networking.wg-quick.interfaces.wg0.configFile = "/home/hello/Documents/Myxogastria0808-NixOS.conf";
  # nftables is required by Incus (it uses nftables instead of iptables for container networking)
  networking.nftables.enable = true;

  # ── State Version ─────────────────────────────────────────────────────────────
  # Determines the NixOS release from which default settings for stateful data
  # (file locations, database versions) are taken. Do not change this after the
  # initial install unless you fully understand the implications.
  # See: https://nixos.org/nixos/options.html
  system.stateVersion = "25.11";
}
